### ISSUE TITLE
Fetches all spaces at startup, which fails when slow CC and lots of spaces

### ISSUE THREAD

**Issue by gberche-orange** [Orange-OpenSource/elpaaso-sandbox-service#17]
Sandbox-service fails to start with a slow CC

Turning on logging traces 

```
    cf set-env elpaaso-sandbox-service APP_LOGGING_LEVEL DEBUG
    cf set-env elpaaso-sandbox-service logging.level.org.springframework DEBUG
```

we observed traces show that all spaces (~2,200) are loaded at sandbox-service startup:

```
       2019-08-30T10:29:25.01+0200 [APP/PROC/WEB/1] OUT 2019-08-30 08:29:25.014 DEBUG 6 --- [           main] org.apache.http.headers                  : http-outgoing-0 >> GET /v2/spaces?inline-relations-depth=1&order-direction=asc&page=9&results-per-page=50 HTTP/1.1
```

Root cause is the old cf-java-client lib used #15 which fetches all spaces on startup in its constructor `CloudControllerClientImpl(URL cloudControllerUrl, RestTemplate restTemplate,
	                                 OauthClient oauthClient, LoggregatorClient loggregatorClient,
	                                 CloudCredentials cloudCredentials, String orgName, String spaceName)`

https://github.com/cloudfoundry/cf-java-client/blob/3978329ec83ff67661f69fadcef089bcd86e7b12/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClientImpl.java#L162-L173
https://github.com/cloudfoundry/cf-java-client/blob/3978329ec83ff67661f69fadcef089bcd86e7b12/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClientImpl.java#L2525-L2527

Options:
1- bump cf-java-client see #15
2- try to workaround by not assigning a default space in the cloudofoundry client, since org/space is already propagated through CloudfoundryTarget instance variable

https://github.com/orange-cloudfoundry/elpaaso-sandbox-service/blob/ae8e79581a466249f1807c57b3c446713a70c655/src/main/java/com/orange/clara/cloud/services/sandbox/infrastructure/CloudfoundryPrivateSandboxService.java#L39-L57

3- try to workaround by using the other constructor still assigning a default space `public CloudControllerClientImpl(URL cloudControllerUrl, RestTemplate restTemplate, OauthClient oauthClient, LoggregatorClient loggregatorClient,CloudCredentials cloudCredentials, CloudSpace sessionSpace)`

```java
private CloudEntityResourceMapper resourceMapper = new CloudEntityResourceMapper();
Map<String, Object> resource = // map Json output from a response from "/v2/spaces?inline-relations-depth=1&q=name:{name}";
CloudSpace space = resourceMapper.mapResource(resource, CloudSpace.class);
```

**Comment by gberche-orange** [comment]
Not clear how to release a new version:
- current process is relying on jfrog oss, not clear credentials are still valid since 2015
- build process seems to depend on files such as `JFROG_PROMOTION_URL=$(cat JFrogPromotion.url)` which may be dependent on a settings in the old travis-ci project before the github repository move from orangeopen-source to orange-cloudfoundry

Paas-templates is currently deploying https://oss.jfrog.org/artifactory/oss-release-local/com/orange/clara/cloud/services/sandbox/elpaaso-sandbox-service/1.0.36/elpaaso-sandbox-service-1.0.36.jar

however this is not the latest build, see 1.0.67 at 

https://oss.jfrog.org/artifactory/oss-release-local/com/orange/clara/cloud/services/sandbox/elpaaso-sandbox-service/

current tags 

```
git tag -l
releases/1.0.63-SNAPSHOT
releases/1.0.65-SNAPSHOT
releases/1.0.67-SNAPSHOT
```

=> Attempting to merge PR, and see what happens

**Comment by gberche-orange** [comment]
https://travis-ci.org/orange-cloudfoundry/elpaaso-sandbox-service/builds/578834559 produced https://oss.jfrog.org/oss-snapshot-local/com/orange/clara/cloud/services/sandbox/elpaaso-sandbox-service/1.0.112-SNAPSHOT available in https://oss.jfrog.org/artifactory/oss-snapshot-local/com/orange/clara/cloud/services/sandbox/elpaaso-sandbox-service/1.0.112-SNAPSHOT/elpaaso-sandbox-service-1.0.112-20190830.140552-1.jar

**Comment by gberche-orange** [comment]
Feedback by @o-orand:
- risk that space is needed in admin client (would issue error messages)
- other pending untested commits in master (between are likely to introduce regression.
- test procedure
  - on integration pf:
      - need to setup sandbox-ui: need to fix configuration (points to uaa client prod)
   - quick test (if run in production): delete an existing user space + its membership in orange-private-sandbox + remove user
   - full test: create a new user (and remove it afterwards if run on production)

=> decision to postpone deployment of this patch

**Comment by gberche-orange** [comment]
Here is a stack trace obtained from triggering a thread dump. The threaddump was not possible to obtain through ssh when the health check type was http, as ssh connection to the container was rejected. Transiently modifying the health check type to "process" enabled `cf ssh` connection from which a `kill -3 <PID>` was launched (PID of the JRE, possibly always 6)

```
  2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	- locked <0x00000000f02356b0> (a java.lang.Object)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	- locked <0x00000000f02356c0> (a sun.security.ssl.AppInputStream)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.rest.LoggingRestTemplate.doExecute(LoggingRestTemplate.java:54)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.addPageOfResources(CloudControllerClientImpl.java:1239)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getAllResources(CloudControllerClientImpl.java:1232)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getSpaces(CloudControllerClientImpl.java:647)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.validateSpaceAndOrg(CloudControllerClientImpl.java:202)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.<init>(CloudControllerClientImpl.java:178)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.rest.CloudControllerClientFactory.newCloudController(CloudControllerClientFactory.java:78)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.CloudFoundryClient.<init>(CloudFoundryClient.java:164)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.CloudFoundryClient.<init>(CloudFoundryClient.java:151)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at com.orange.clara.cloud.services.sandbox.ElpaasoSandboxServiceApplication.getCloudFoundryClientAsAdmin(ElpaasoSandboxServiceApplication.java:67)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at com.orange.clara.cloud.services.sandbox.ElpaasoSandboxServiceApplication$$EnhancerBySpringCGLIB$$9f88f39f.CGLIB$getCloudFoundryClientAsAdmin$2(<generated>)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at com.orange.clara.cloud.services.sandbox.ElpaasoSandboxServiceApplication$$EnhancerBySpringCGLIB$$9f88f39f$$FastClassBySpringCGLIB$$de90e6bf.invoke(<generated>)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318)
   2019-09-02T11:17:15.12+0200 [APP/PROC/WEB/0] OUT 	at com.orange.clara.cloud.services.sandbox.ElpaasoSandboxServiceApplication$$EnhancerBySpringCGLIB$$9f88f39f.getCloudFoundryClientAsAdmin(<generated>)
```

**Comment by gberche-orange** [comment]
Confirmed that space is necessary in CC API version

```
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT java.lang.IllegalArgumentException: Unable to create a new space without specifying organization and space to use.
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.util.Assert.notNull(Assert.java:115) ~[spring-core-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.assertSpaceProvided(CloudControllerClientImpl.java:2022) ~[cloudfoundry-client-lib-1.1.4.ORANGEv19.jar!/:na]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.createSpace(CloudControllerClientImpl.java:580) ~[cloudfoundry-client-lib-1.1.4.ORANGEv19.jar!/:na]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.lib.CloudFoundryClient.createSpace(CloudFoundryClient.java:583) ~[cloudfoundry-client-lib-1.1.4.ORANGEv19.jar!/:na]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at com.orange.clara.cloud.services.sandbox.infrastructure.CloudfoundryPrivateSandboxService.createSandboxForUser(CloudfoundryPrivateSandboxService.java:50) ~[app/:na]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at com.orange.clara.cloud.services.sandbox.application.SandboxService.createSandbox(SandboxService.java:49) ~[app/:na]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at com.orange.clara.cloud.services.sandbox.web.SandboxController.register(SandboxController.java:49) ~[app/:na]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-09-02T12:14:58.71+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
```

```
	@Override
	public void createSpace(String spaceName) {
		assertSpaceProvided("create a new space");
		UUID orgGuid = sessionSpace.getOrganization().getMeta().getGuid();
		UUID spaceGuid = getSpaceGuid(spaceName, orgGuid);
		if (spaceGuid == null) {
			doCreateSpace(spaceName, orgGuid);
		}
	}
```

=> reverted fix in 532f6cd
